server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

scrape_configs:
- job_name: metrics
  static_configs:
  - targets:
      - - 127.0.0.1
    labels:
      job: my_job
