# coding: utf-8

# flake8: noqa
"""
    Movies API

    API для работы с фильмотекой  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import models into model package
from swagger_client.models.movie import Movie
