name: CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run tests
      run: |
        pytest tests/
        
  deploy:
    needs: test
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Deploy to server
      env:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.DOCKER_USERNAME }}
        PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        ssh $USERNAME@$HOST 'cd /path/to/your/project && git pull'
        scp -r . $USERNAME@$HOST:/path/to/your/project
        ssh $USERNAME@$HOST 'cd /path/to/your/project && docker build -t your-app .'
        ssh $USERNAME@$HOST 'cd /path/to/your/project && docker run -d -p 8080:8080 your-app'
    - name: Update Swagger documentation
      env:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.DOCKER_USERNAME }}
        PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        scp -r your-swagger-files $USERNAME@$HOST:/path/to/your/swagger/docs
        ssh $USERNAME@$HOST 'cd /path/to/your/swagger/docs && docker build -t swagger-docs .'
        ssh $USERNAME@$HOST 'cd /path/to/your/swagger/docs && docker run -d -p 8081:8080 swagger-docs'
