name: CI/CD Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  ci:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Install Docker
      run: |
        sudo apt-get update
        sudo apt-get install -y docker.io
        sudo systemctl start docker
        sudo systemctl enable docker
        
    - name: Build Docker images
      run: docker-compose build
      
    - name: Run tests
      run: docker-compose run app npm test
      
  cd:
    needs: ci
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Install Docker
      run: |
        sudo apt-get update
        sudo apt-get install -y docker.io
        sudo systemctl start docker
        sudo systemctl enable docker
        
    - name: Generate deployment package
      run: zip -r deploy.zip . -x '*.git*'
      
    - name: Deploy to staging
      env:
        HOST: ${{ secrets.STAGING_HOST }}
        USER: ${{ secrets.STAGING_USER }}
        KEY: ${{ secrets.STAGING_SSH_KEY }}
      run: |
        mkdir -p ~/.ssh
        echo "$KEY" > ~/.ssh/staging.key
        chmod 600 ~/.ssh/staging.key
        scp -i ~/.ssh/staging.key ./deploy.zip $USER@$HOST:/path/to/project
        ssh -i ~/.ssh/staging.key $USER@$HOST "
          cd /path/to/project
          rm -rf *
          unzip -o deploy.zip
          docker-compose down
          docker-compose up -d
        "
        
    - name: Deploy to production
      if: success() && github.ref == 'refs/heads/main'
      env:
        HOST: ${{ secrets.PROD_HOST }}
        USER: ${{ secrets.PROD_USER }}
        KEY: ${{ secrets.PROD_SSH_KEY }}
      run: |
        mkdir -p ~/.ssh
        echo "$KEY" > ~/.ssh/prod.key
        chmod 600 ~/.ssh/prod.key
        scp -i ~/.ssh/prod.key ./deploy.zip $USER@$HOST:/path/to/project
        ssh -i ~/.ssh/prod.key $USER@$HOST "
          cd /path/to/project
          rm -rf *
          unzip -o deploy.zip
          docker-compose down
          docker-compose up -d
        "
