name: Docker Compose

on:
  push:
    branches:
      - main

jobs:

  docker-compose:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Build and run Docker Compose
      run: |
        docker-compose up -d
        
    - name: Check running containers
      run: docker-compose ps
        
    - name: Follow logs
      run: docker-compose logs --follow
