name: Swagger Server

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  run-swagger-server:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r server/requirements.txt
        pip install prometheus_client
    - name: Run Swagger Server
      run: |
        cd server
        python -m swagger_server.__main__

  run-client:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r client/requirements.txt
        pip install prometheus_client
    - name: Run Client
      run: |
        cd client
        python main.py
